version: '3'
services:
  db:
    image: mysql:5.7
    volumes:
      - mysql-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exchanger
    ports:
      - "3306:3307"
volumes:
  mysql-db: