spring:
  cloud:
    openfeign:
      client:
        config:
          currency:
            url: http://api.nbp.pl/api/exchangerates/tables/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://127.0.0.1:3307/exchanger"
    username: "root"
    password: ""
    testOnBorrow: true
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    max-active: 15
    max-idle: 10
    max-wait: 8000