spring:
  cloud:
    openfeign:
      client:
        config:
          currency:
            url: http://api.nbp.pl/api/exchangerates/tables/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
          holidays:
            url: https://date.nager.at/api/v3/PublicHolidays/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/exchanger
    username: root
    password:
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  sql:
    init:
      mode: always
repository:
  mock:
    holidays:
      mock:
        enable: false
    currency:
      mock:
        enable: false
