spring:
  cloud:
    openfeign:
      client:
        config:
          currency:
            url: http://api.nbp.pl/api/exchangerates/tables/
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: full
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3307/exchanger'
    username: 'root'
    password: 
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
  batch:
    jdbc:
      initialize-schema: always
